### PR TITLE
Changed CRD version back to v1beta1 

### PR DESCRIPTION
**Pull request by lintongj**
Changed CRD version back to v1beta1 for supporting vsphere plugin in pre-1.16 k8s clusters

Testing:

1. Unit Test: Passed (i.e., run make test or make ci)
2. Precheckin:
   - Vanilla: Passed (Job: Container_Precheck_Velero 720).

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/367/

**Comment by xing-yang** [comment]
The change looks fine.

**Review by deepakkinni — APPROVED** [review]
lgtm

**Review by xing-yang — APPROVED** [review]
LGTM

**Pull request merged**
