### PR TITLE
[Crossport] Updated the workflow of release.yml to rebuild when releasing a new version

### PR DESCRIPTION
**Pull request by lintongj**
Signed-off-by: Lintong Jiang <lintongj@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by xing-yang** [comment]
LGTM

**Comment by lintongj** [comment]
> LGTM

Hi Xing @xing-yang , would you please approve it? Approval is required for the merge.

**Review by deepakkinni — APPROVED** [review]
lgtm

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/630/

**Pull request merged**
