### PR TITLE
[Cherry-pick] Add newer crds in supervisor cluster to block list

### PR DESCRIPTION
**Pull request by xinyanw409**
Signed-off-by: xinyanw409 <wxinyan@vmware.com>

**What this PR does / why we need it**:
This is a cherry pick PR for #459 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Cherry-pick #459: Update exclude list for backup driver on supervisor cluster.
```

### CODE REVIEW

**Comment by xing-yang** [comment]
@xinyanw409 Can you remove the bug number from your commit message?

**Comment by xinyanw409** [comment]
> @xinyanw409 Can you remove the bug number from your commit message?

@xing-yang Removed pr number from commit message.

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/720/

**Review by xing-yang — APPROVED** [review]
LGTM

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/721/

**Pull request merged**
