### PR TITLE
Changed RestoreItemAction back to using Item for most uses so that ch…

### PR DESCRIPTION
**Pull request by dsu-igeek**
…anges made by previous

plugins on the item are kept

Signed-off-by: Dave Smith-Uchida <dsmithuchida@vmware.com>

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/239/

**Comment by xing-yang** [comment]
The change looks good. 

Can you take a look of the pre-check failure?

**Comment by xing-yang** [comment]
Testing this fix on Supervisor Cluster: https://container-dp.svc.eng.vmware.com/job/CNSDP_WCP_CI/34/console

**Comment by xing-yang** [comment]
I see the same problem on Supervisor Cluster again after restore, but then I realized this CI pipeline is not enabled to run the new plugin:(.

```
# kubectl get all -n test-cns-dp-wcp-ns-xrlarfk
NAME                        READY   STATUS           RESTARTS   AGE
pod/etcd0                   0/1     ProviderFailed   0          19m
pod/jump-pad                0/1     ProviderFailed   0          19m
pod/kibishii-deployment-0   0/1     Pending          0          19m
pod/kibishii-deployment-1   0/1     ProviderFailed   0          19m

NAME                  TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
service/etcd-client   ClusterIP   10.96.0.35    <none>        2379/TCP            19m
service/etcd0         ClusterIP   10.96.0.145   <none>        2379/TCP,2380/TCP   19m

NAME                                   READY   AGE
statefulset.apps/kibishii-deployment   0/2     19m
```

**Comment by xing-yang** [comment]
Enabled the new plugin on Supervisor Cluster and manually tested it.  It works.

```
# kubectl get all -n test-cns-dp-wcp-ns-xrlarfk
NAME                        READY   STATUS    RESTARTS   AGE
pod/etcd0                   1/1     Running   0          2m3s
pod/jump-pad                1/1     Running   0          2m3s
pod/kibishii-deployment-0   1/1     Running   0          2m3s
pod/kibishii-deployment-1   1/1     Running   0          2m2s

NAME                  TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)             AGE
service/etcd-client   ClusterIP   10.96.0.6     <none>        2379/TCP            2m3s
service/etcd0         ClusterIP   10.96.0.226   <none>        2379/TCP,2380/TCP   2m3s

NAME                                   READY   AGE
statefulset.apps/kibishii-deployment   2/2     2m3s
```

**Review by lintongj — APPROVED** [review]
/lgtm

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/244/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/247/

**Comment by xing-yang** [comment]
Tested on Vanilla test bed.  It works.

**Pull request merged**
