### PR TITLE
Updated to astrolabe latest for missing block fix

### PR DESCRIPTION
**Pull request by dsu-igeek**
Signed-off-by: Dave Smith-Uchida <dsmithuchida@vmware.com>

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/184/

**Comment by xing-yang** [comment]
CI failed with the following error:
```
21:15:55 2020-09-01T01:15:55.069Z [ERROR vsanTestClass.py::runTestSetup::436::MainThread] Test exception: vsphere-cloud-controller-manager pod is not up even after 5 minutes of wait time
```

**Comment by xing-yang** [comment]
LGTM

**Comment by dsu-igeek** [comment]
Superceded

**Pull request closed without merging**
