### PR TITLE
[Crossport] Updated client-go dep from v0.18.4 to v0.22.0

### PR DESCRIPTION
**Pull request by lintongj**
Signed-off-by: Lintong Jiang <lintongj@vmware.com>

**What this PR does / why we need it**:

Crossport #402 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/633/

**Comment by xing-yang** [comment]
LGTM

**Comment by lintongj** [comment]
rerun tests

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/634/

**Comment by lintongj** [comment]
rerun tests

**Review by deepakkinni — APPROVED** [review]
lgtm

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/635/

**Pull request merged**
