### PR TITLE
Bumping up the velero version to v1.5.1

### PR DESCRIPTION
**Pull request by lintongj**
Bumping up the velero version to v1.5.1

Signed-off-by: Lintong Jiang <lintongj@vmware.com>

Testing:

Running the precheckin test manually: https://container-dp.svc.eng.vmware.com/job/Container_Precheck_Velero/538/ (The only failed case is because the restore takes about 2 hours to complete while the test sets the timeout to be 1 hour. )

### CODE REVIEW

**Comment by xing-yang** [comment]
Do we have a check for velero version anywhere in the plugin code?  Maybe that's only in the Velero App Operator.

**Comment by lintongj** [comment]
> Do we have a check for velero version anywhere in the plugin code? Maybe that's only in the Velero App Operator.

Thanks Xing. We do need to update minimum version of Velero in plugin code base.

**Comment by xing-yang** [comment]
LGTM

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/257/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/258/

**Review by deepakkinni — APPROVED** [review]
lgtm, let the QE know to change the version on Jenkins job

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/260/

**Pull request merged**
