### PR TITLE
Updated client-go dep from v0.18.4 to v0.22.0

### PR DESCRIPTION
**Pull request by lintongj**
**What this PR does / why we need it**:

Updated client-go dep from v0.18.4 to v0.22.0 and resolved dependencies

**Which issue(s) this PR fixes**:

To resolve dependencies.

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Updated client-go dep from v0.18.4 to v0.22.0
```

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/631/

**Review by deepakkinni — APPROVED** [review]
lgtm

**Comment by lintongj** [comment]
rerun tests

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/632/

**Comment by xing-yang** [comment]
LGTM

**Pull request merged**
