### PR TITLE
Updated docs about the plugin install with customized images

### LINKED ISSUE #378: velero plugin for vsphere in air-gapped environment
I see some other references to this but none others seem to exactly match my situation.

I'm installing velero, and the velero plugin for aws, and velero plugin for vsphere in an air-gapped environment. I'm installing using the helm chart https://github.com/vmware-tanzu/helm-charts/releases/tag/velero-2.23.3

I'm specifying the following in the `initContainers` list of the `values.yaml` for the vsphere plugin:
```
- name: velero-plugin-for-vsphere
  image: my-internal-registry/velero/vsphereveleroplugin-velero-plugin-for-vsphere:v1.1.1
```
As a result, a deployment `backup-driver` is generated by the init container (I'm guessing) with image: `dpcpinternal/backup-driver:v1.1.1-rc4` which of course does not exist in our air-gapped image registry.

I need to have this image ref in the deployment patched to reference our air-gapped registry. Is there a per-design way to do this? If this is already answered elsewhere I apologize.

Thanks

### PR DESCRIPTION
**Pull request by lintongj**
Signed-off-by: Lintong Jiang <lintongj@vmware.com>

**What this PR does / why we need it**:

Updated docs about the plugin install with customized images, which also covers the case of install plugin in air-gapped environment

**Which issue(s) this PR fixes**:

Fixes #378 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/576/

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/577/

**Comment by lintongj** [comment]
@xing-yang @deepakkinni would you please help review this doc change?

**Review by deepakkinni — APPROVED** [review]
lgtm

**Review by xing-yang — APPROVED** [review]
LGTM

**Pull request merged**
