### PR TITLE
Update astrolabe to v0.5.1

### PR DESCRIPTION
**Pull request by xinyanw409**
**What this PR does / why we need it**:
We cut a new release for astrolabe. This PR picks up changes in astrolabe side and update astrolabe version to v0.5.1.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update astrolabe version to v0.5.1.
```

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/732/

**Comment by xinyanw409** [comment]
rerun tests

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/733/

**Review by deepakkinni — APPROVED** [review]

**Review by xing-yang — APPROVED** [review]
LGTM

**Comment by xing-yang** [comment]
@xinyanw409 Please backport this to release-1.4.

**Pull request merged**
