### PR TITLE
Update support matrix for WCP.

### PR DESCRIPTION
**Pull request by lipingxue**
Signed-off-by: Liping Xue lipingx@vmware.com

**What this PR does / why we need it**:
This change is to update WCP compatibility matrix to remove the following row:
Velero Plugin for vSphere Version: 1.4.2
vSphere Version: 7.0U3h
Velero Version: 1.9.2
Velero vSphere Operator Version: 1.3.0
Data Manager Version: 1.2.0

The reason we need to remove the above combination is because Velero vSphere Operator Pod will restart periodically with this combination and may cause installing Velero vSphere plugin in TKC failed. 

The following are detail explanations for this issue:
1. During Velero vSphere operator reconcile, when a TKC is created, operator need to create a ProviderServiceAccount CR. Tkc controller watches for these PSA and creates a secret in specific guest clusters. (PSA account and secret are required to install Velero vSphere plugin in guest cluster). In this case, the operator failed to create ProviderServiceAccount CR since it is crashed. Therefore, installing Velero vSphere plugin in TKC will fail.
2. we found that if TKC is created before Velero vSphere Operator pod is created, PSA account and secret may be created before the Velero vSphere Operator Pod crashed. In this case, installing Velero vSphere plugin in TKC will succeed. But this no guarantee that this combination will work all the time. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```NONE

```

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/825/

**Comment by xing-yang** [comment]
The change LGTM.
Can you fix DCO?

**Comment by lipingxue** [comment]
> The change LGTM. Can you fix DCO?

Fixed. Please take a look. @xing-yang

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/826/

**Review by xing-yang — APPROVED** [review]
lgtm

**Pull request merged**
