### PR TITLE
Handle the case where PVC has not specified StorageClass

### PR DESCRIPTION
**Pull request by xing-yang**
Need to check if StorageClassName is nil before printing it out.

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/188/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/189/

**Review by lintongj — APPROVED** [review]
/lgtm

**Review by deepakkinni — APPROVED** [review]
lgtm

**Pull request merged**
