### PR TITLE
Update go.mod to pick up changes to upgrade golang version to 1.17 in astrolabe side

### PR DESCRIPTION
**Pull request by xinyanw409**
Signed-off-by: xinyanw409 <wxinyan@vmware.com>

**What this PR does / why we need it**:
This PR picks up changes to upgrade golang version to 1.17 in astrolabe side.
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Test done:
Run ```go mod tidy```
Regression tests.
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/686/

**Comment by xinyanw409** [comment]
rerun tests

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/688/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/689/

**Comment by xinyanw409** [comment]
rerun tests

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/690/

**Comment by xinyanw409** [comment]
rerun tests

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/691/

**Comment by xinyanw409** [comment]
rerun tests

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/692/

**Comment by xinyanw409** [comment]
rerun tests

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/693/

**Comment by xinyanw409** [comment]
rerun tests

**Comment by xinyanw409** [comment]
rerun tests

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/695/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/1/

**Comment by xinyanw409** [comment]
Precheck passed: https://container-dp.svc.eng.vmware.com/job/Container_Precheck_Velero/1340/

**Review by lintongj — APPROVED** [review]

**Pull request merged**
