### PR TITLE
Updated to use astrolabe v0.1.0

### PR DESCRIPTION
**Pull request by dsu-igeek**

### CODE REVIEW

**Comment by lintongj** [comment]
Looks good. But, there is no v0.1.0 branch in astrolabe for the moment. Would it be a problem?

**Comment by dsu-igeek** [comment]
> Looks good. But, there is no v0.1.0 branch in astrolabe for the moment. Would it be a problem?

I added a v0.1.0 tag, that's how the releases are designated.  go get works anyhow

**Comment by lintongj** [comment]
> > Looks good. But, there is no v0.1.0 branch in astrolabe for the moment. Would it be a problem?
> 
> I added a v0.1.0 tag, that's how the releases are designated. go get works anyhow

I didn't check the tag list. It should be OK.

**Comment by dsu-igeek** [comment]
Green precheckin test - https://container-dp.svc.eng.vmware.com/job/Container_Precheck_Velero/61/

**Pull request merged**
