### PR TITLE
Fix datamgr daemonset

### PR DESCRIPTION
**Pull request by c3y1huang**
Fix for datamgr daemonset to launch. 

Changes includes:
* non-existent service account.
* align secret with with velero server.

Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>

### CODE REVIEW

**Comment by c3y1huang** [comment]
ref: https://github.com/SUSE/avant-garde/issues/1221

**Comment by lintongj** [comment]
I really don't see any reason why do we need to make this change.

**Comment by c3y1huang** [comment]
For me it seems datamgr doesn’t launch after plugin added. This fix mostly to align with Velero server and reuse the available resource and make datamgr work out of the box.

**Comment by lintongj** [comment]
> For me datamgr doesn’t launch after plugin added. This fix mostly to align with Velero server and reuse the available resource and make datamgr work out of the box.

I am wondering it might be because when the velero was installed in your cluster, the ServiceAccountName was set to `velero-server`, while the SecretName was set to `velero`.  That's the reason why you need to make the change in this commit to get aligned with. 

The values set in the Datamgr Daemonset in the current code base is aligned with the default value of ServiceAccountName and SecretName in velero github repo. Feel free to refer to https://github.com/vmware-tanzu/velero/blob/master/pkg/install/daemonset.go and https://github.com/vmware-tanzu/velero/blob/master/pkg/install/deployment.go. So, we don't see any problem with it.

Additionally, different users of velero and vsphere plugin might have different configurations about ServiceAccountName and SecretName for velero. So, this change might not be generally useful. 

Instead, retrieving suitable ServiceAccountName and SecretName from velero deployment for Datamgr Daemonset would be more widely effective.

**Comment by c3y1huang** [comment]
Ahh. I see. Closing this and I will check where we are getting those from. Thanks for the explanation.

**Pull request closed without merging**
