### PR TITLE
Add pushing image to GCR action in ci.yaml

### PR DESCRIPTION
**Pull request by blackpiglet**
Signed-off-by: Xun Jiang <jxun@vmware.com>

**What this PR does / why we need it**:
Push images to gcr.io/velero-gcp repository and tag them by PR's branch name, when the event type is push request.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/705/

**Comment by blackpiglet** [comment]
It looks like that the error is triggered due to secret is not passed to Action.

[Secrets are not passed to the runner when a workflow is triggered from a forked repository.](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow)

**Comment by blackpiglet** [comment]
> Sorry, some of the pre-check tests are failing for this PR !
> 
> Please check the Jenkins job for more details https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/705/

I found this in the Jenkins job.
04:30:38  denied: adding 34.2 MiB of storage resource, which when updated to current usage of 20.0 GiB will exceed the configured upper limit of 20.0 GiB.

Looks like the storage limit hit.

**Comment by lintongj** [comment]
@blackpiglet FYI, the docker/login action works just fine for https://github.com/vmware-tanzu/velero-plugin-for-vsphere/runs/5592107778?check_suite_focus=true. The action scripts are just the same.

**Comment by blackpiglet** [comment]
> 

@lintongj Thanks. Even if I use username and password instead, it would be same result, because `secrets are not passed to the runner when a workflow is triggered from a forked repository.` password and username are also stored in secrets.

**Comment by blackpiglet** [comment]
> @blackpiglet FYI, the docker/login action works just fine for https://github.com/vmware-tanzu/velero-plugin-for-vsphere/runs/5592107778?check_suite_focus=true. The action scripts are just the same.

It's surprised this action is used in the other runs. The PR is not merged yet.
It did prove this PR should work as expected, although checks failed here due to [Secrets are not passed to the runner when a workflow is triggered from a forked repository.](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow)

**Comment by lintongj** [comment]
> > Looks like the action docker/login-action@v1 is not so reliable. I referred [this article](https://github.community/t/keep-getting-error-username-and-password-required/191717/2). To push to GCR, maybe you want to try something similar to
> 
> @lintongj Thanks. Even if I use username and password instead, it would be same result, because `secrets are not passed to the runner when a workflow is triggered from a forked repository.` password and username are also stored in secrets, and unfortunately, this PR is triggered from my fork repository, furthermore my PR content requires access to secrets information.

That makes sense. What we've been doing is aligned with the constraint of github action `secrets are not passed to the runner when a workflow is triggered from a forked repository`.
(1) When submit a pull request, run build and unit test (without triggering image push)
(2) When the pull request is merged, run build, unit test and then push image. 

Meanwhile, I don't see much value in pushing images to the official image registry(which require password authentication) when submitting each pull request.

**Comment by blackpiglet** [comment]
By far, there is no need for change. Close it.

**Pull request closed without merging**
