### PR TITLE
Move ivd Astrolabe plugin into Velero Plugin for vSphere

### PR DESCRIPTION
**Pull request by dsu-igeek**
**What this PR does / why we need it**:
Moves IVD (Improved Virtual Disk/First Class Disk) from astrolabe core into Velero Plug-in for vSphere

**Does this PR introduce a user-facing change?**:

```release-note
Moved the vSphere specific ivd Protected Entity from Astrolabe into Velero Plugin for vSphere, no functionality
changes in the IVD PE otherwise. Added vsphere-astrolabe CLI tool that can interact with IVDs
```

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/583/

**Comment by xing-yang** [comment]
/hold

We need to make sure this is thoroughly tested before merging.

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/584/

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/585/

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/586/

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/587/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/588/

**Comment by xing-yang** [comment]
@dsu-igeek How do we support astrolabe CLI now ivd is moved here?

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/603/

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/604/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/606/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/607/

**Review by deepakkinni — COMMENTED** [review]
Hi Dave, this looks good to me, most of it is a move from astrolabe. It'd be great if you updated the PR description and squash your commits. Please post the test results for wcp setups.

**Review by lintongj — COMMENTED** [review]
Looks good to me. I am OK with this change as long as regression test get passed. BTW, would you please fill in the section of `Does this PR introduce a user-facing change?` with a changelog message even though it is not user facing? We use it to auto-generate changelog for releases.

**Comment by dsu-igeek** [comment]
WCP test run passed, results are here - https://container-dp.svc.eng.vmware.com/view/CNS-DP-WIP/job/TestWCP-2/814/consoleFull

**Review by lintongj — APPROVED** [review]
Looks good. @dsu-igeek I updated the PR release note to be one-liner, which is expected by the release-notes tool.

**Review by deepakkinni — APPROVED** [review]
lgtm

**Comment by xing-yang** [comment]
Hi @dsu-igeek, how to use "vsphere-astrolabe" CLI?  Does it take the same arguments as the original astrolabe CLI?

**Comment by dsu-igeek** [comment]
> Hi @dsu-igeek, how to use "vsphere-astrolabe" CLI? Does it take the same arguments as the original astrolabe CLI?

Yes, it's exactly the same.  Only difference is the ivd plugin is compiled into it and I'll be removing the ivd plugin from astrolabe proper so the Astrolabe version won't have ivd compiled into it.

**Comment by xing-yang** [comment]
LGTM

**Comment by svcbot-qecnsdp** [comment]
Congratulations !! 

All the pre-check tests passed
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/610/

**Pull request merged**
