### PR TITLE
[Crossport] Add docs for self-signed cert (#425)

### PR DESCRIPTION
**Pull request by xinyanw409**
Signed-off-by: xinyanw409 <wxinyan@vmware.com>

**What this PR does / why we need it**:
This pr is a cherry-pick for #425 
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lintongj** [comment]
@xing-yang do we usually need release note for doc change?

**Comment by xing-yang** [comment]
We don't need release note for doc PR.

**Comment by xinyanw409** [comment]
Remove release note.

**Comment by xing-yang** [comment]
LGTM

**Review by xing-yang — APPROVED** [review]

**Review by lintongj — APPROVED** [review]

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/661/

**Pull request merged**
