### PR TITLE
Fixed incorrect version number set on containers

### PR DESCRIPTION
**Pull request by dsu-igeek**

### CODE REVIEW

**Comment by lintongj** [comment]
This change is unnecessary. Because the version is set at the rule `_output/bin/$(GOOS)/$(GOARCH)/$(BIN)`, which is the indirect dependency of both `plugin` and `datamgr` rules. That means, as long as there is version set along with the make command, the version will be set properly.

**Comment by dsu-igeek** [comment]
With the makefile setting the version as a make variable it needs to be passed down.  Without this, the version number gets regenerated.

**Comment by lintongj** [comment]
Actually, I always run `make push VERSION=xxx`. The version is always tagged to image as expected. Meanwhile, the version is also successfully passed to the built binary through go linker flag. Did you run into any unexpected case?

**Comment by dsu-igeek** [comment]
The whole point of the change is that you don't need to set VERSION=xxx outside, but that the Makefile will generate the correct version

**Comment by lintongj** [comment]
Oh, i see. Looks good to me now.

**Pull request merged**
