### PR TITLE
Claim Backup Repository

### PR DESCRIPTION
**Pull request by deepakkinni**
On install, a call is made to ClaimBackupRepository which is responsible for creating a BRC and waiting for BR to be associated with it.

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/7/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/11/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/13/

**Comment by deepakkinni** [comment]
This is present in sprint-07-02-2020, closing this.

**Pull request closed without merging**
