### PR TITLE
[Draft] Remove glibc dependency long term

### LINKED ISSUE #466: Is it possible to remove the dependency for glibc inside the Velero image
Velero uses the [gcr.io/distroless/base-debian11](https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md) as the base image while the `base-debian` contains several CVEs introduced by `glibc` and some other packages.

Currently, only vSphere plugin needs the `glibc` inside the Velero image, so is it possible to remove the dependency for `glibc` inside Velero image so that Velero can use [gcr.io/distroless/static-debian11](https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md) instead? e.g. resolve the dependency in vSphere plugin side?

The [gcr.io/distroless/static-debian11](https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md) contains fewer packages and that means it contains fewer CVEs and we don't need to release patches to fix them, that will save us a lot of time.

### PR DESCRIPTION
**Pull request by xinyanw409**
**What this PR does / why we need it**:
This PR tends to spin data-manager binary into two different ones, install and server. In this way both vsphere plugin image and backup-driver image can get rid of dependency of glibc.
**Which issue(s) this PR fixes**:

Fixes #466

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/743/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/744/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/755/

**Comment by svcbot-qecnsdp** [comment]
Sorry, some of the pre-check tests are failing for this PR ! 

Please check the Jenkins job for more details
https://container-dp.svc.eng.vmware.com/job/CNSDP-CI/756/

**Comment by ywk253100** [comment]
@xinyanw409 The vsphere-plugin itself depends on `github.com/vmware/virtual-disks` which needs glibc:
```
go mod why -m github.com/vmware/virtual-disks
# github.com/vmware/virtual-disks
github.com/vmware-tanzu/velero-plugin-for-vsphere/pkg/ivd
github.com/vmware/virtual-disks/pkg/disklib
```
https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/main/cmd/velero-plugin-for-vsphere/main.go#L25

https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/0bfbef3a206c4c5dcce5076b9fc42c95344c59cd/pkg/plugin/volume_snapshotter_plugin.go#L24

https://github.com/vmware-tanzu/velero-plugin-for-vsphere/blob/0bfbef3a206c4c5dcce5076b9fc42c95344c59cd/pkg/snapshotmgr/snapshot_manager.go#L26

So the dependency should be removed to make sure vsphere-plugin can run in an environment that has no glibc.

Correct me if I'm wrong.

**Pull request closed without merging**
